CorporatePortal/CorporatePortal/Models/CreditNotes/AddCreditNotePageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorporatePortal.Models.CreditNotes
{
    public class AddCreditNotePageModel
    {
        public int? CreditProfileId { get; set; }

        public string CreditProfileName { get; set; }

        public IList<SelectListItem> CreditProfiles { get; set; }

        public IList<SelectListItem> Types { get; set; }

        public string StatementType { get; set; }

        public string Type { get; set; }

        public bool Paid { get; set; }

        public string Description { get; set; }

        public double TotalSpent { get; set; }
    }
}

CorporatePortal/CorporatePortal/Models/CreditNotes/CreditNotesPageModel.cs
using CorporatePortal.Api.Requests.CredNotes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.CreditNotes
{
    public class CreditNotesPageModel
    {
        public List<CreditNoteModel> CreditNotes { get; set; }
    }
}

CorporatePortal/CorporatePortal/Models/CreditNotes/UpdateCreditNotePageModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.CreditNotes
{
    public class UpdateCreditNotePageModel
    {
        public int CreditNoteId { get; set; }

        public int CreditProfileId { get; set; }

        public string CreditProfileName { get; set; }
        
        public string StatementType { get; set; }
     
        public DateTime CreatedDate { get; set; }

        public double Amount { get; set; }
        
        public string Description { get; set; }

    }
}

CorporatePortal/CorporatePortal/Controllers/CreditNoteController.cs
using CorporatePortal.Api;
using CorporatePortal.Api.Requests.CredNotes;
using CorporatePortal.Models.CreditNotes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorporatePortal.Controllers
{
    public class CreditNoteController : Controller
    {

        IApiService _apiService;

        public CreditNoteController(IApiService apiService)
        {
            _apiService = apiService;
            var model = _apiService.GetPortalSummary();
            ViewBag.TopTiles = model.Summary;
        }

        public ActionResult Index()
        {
            var response = _apiService.GetCreditNotes();

            var list = response.CreditNotes.OrderByDescending(c => c.CreatedDate).ToList();

            var model = new CreditNotesPageModel
            {
                CreditNotes = list
            };

            return View(model);
        }

        public ActionResult Create()
        {
            var model = new AddCreditNotePageModel();

            model.CreditProfiles = GetCreditProfilesDdl();
            model.Types = GetTypeList();
            model.StatementType = "Credit";
            
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(AddCreditNotePageModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var credProf = _apiService.GetCreditProfileById(model.CreditProfileId.Value);

            var request = new AddCreditNoteRequestModel
            {
                CreditProfileId = model.CreditProfileId.Value,
                CreditProfileName = credProf.CreditProfile.ProfileName,
                Description = model.Description,
                StatementType = "Credit",
                TotalSpent = model.TotalSpent,
                Type = model.Type
            };

            var response = _apiService.AddCreditNote(request);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,CorporateAdmin,CorporateManager")]
        [HttpGet]
        public ActionResult DeleteCreditNote(int creditNoteId)
        {
            var response = _apiService.DeleteCreditNote(creditNoteId);

            return RedirectToAction("Index");
        }

        public ActionResult Update(int creditNoteId)
        {
            var response = _apiService.GetCreditNoteById(creditNoteId);

            var model = new UpdateCreditNotePageModel
            {
                CreditNoteId = response.CreditNote.CreditNoteId,
                Amount = response.CreditNote.TotalSpent,
                CreatedDate = response.CreditNote.CreatedDate,
                CreditProfileId = response.CreditNote.CreditProfileId,
                CreditProfileName = response.CreditNote.CreditProfileName,
                Description = response.CreditNote.Description,
                StatementType = response.CreditNote.StatementType
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(UpdateCreditNotePageModel model)
        {
            var request = new UpdateCreditNoteRequestModel
            {
               Description = model.Description,
               Amount = model.Amount,
               statementId = model.CreditNoteId
            };

            var response = _apiService.UpdateCreditNote(model.CreditNoteId, request);

            return RedirectToAction("Index");
        }

        private List<SelectListItem> GetCreditProfilesDdl()
        {
            var list = _apiService.GetCreditProfilesList();

            List<SelectListItem> creditProfilesList = (from p in list.CreditProfileList.AsEnumerable()
                                                       select new SelectListItem
                                                       {
                                                           Text = p.ProfileName,
                                                           Value = p.CreditProfileId.ToString()
                                                       }).ToList();



            creditProfilesList.Insert(0, new SelectListItem { Text = "--Select --", Value = "", Disabled = true, Selected = true });
            creditProfilesList.Insert(1, new SelectListItem { Text = "--None --", Value = "", Disabled = false, Selected = false });
            return creditProfilesList;
        }

        private static List<SelectListItem> GetTypeList()
        {
            List<SelectListItem> statusList = new List<SelectListItem>();
                        
            statusList.Add(new SelectListItem
            {
                Text = "Expensemate Card Spend",
                Value = "EXPENSEMATE 10"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Expensemate Foreign Spend",
                Value = "EXPENSEMATE 10FX"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Expensemate Online Spend",
                Value = "EXPENSEMATE 20"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Expensemate OnLine Foreign Spend",
                Value = "EXPENSEMATE 20FX"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Finance Fee",
                Value = "EXPENSEMATE ADM"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Active Card Fee",
                Value = "EXPENSEMATE CCA"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Issue Card Fee",
                Value = "EXPENSEMATE CCN"
            });

            statusList.Add(new SelectListItem
            {
                Text = "FX Fee Total",
                Value = "EXPENSEMATE FFX"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Expensemate Refund",
                Value = "REFUND"
            });

            statusList.Add(new SelectListItem
            {
                Text = "Bespoke Projects ",
                Value = "EXPENSEMATE"
            });


            //Add Default Item at First Position.
            statusList.Insert(0, new SelectListItem { Text = "--Select --", Value = "", Disabled = true, Selected = true });
            return statusList;
        }
    }
}

CorporatePortal/CorporatePortal/Views/CreditNote/Create.cshtml
@model CorporatePortal.Models.CreditNotes.AddCreditNotePageModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    td {
        font-size: larger;
        padding: 10px;
    }

    .tdlabel {
        font-weight: bold;
    }

    .tdheading {
        color: #69c3c4;
        font-weight: bold;
        font-size: 20px;
    }

    .form-control:focus {
        border-color: #CCD0D7;
        box-shadow: none !important
    }
</style>

<style>
</style>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3></h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>New Credit Note<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <br>
                    @using (Html.BeginForm("Create", "CreditNote",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                    FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.CreditProfileName)

                        <div class="form-group">
                            <span class="control-label col-md-3 col-sm-3 col-xs-12 tdheading">General</span>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CreditProfileId, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DropDownListFor(model => model.CreditProfileId, Model.CreditProfiles, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(model => model.CreditProfileId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DropDownList("Type", Model.Types, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(model => model.Type)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StatementType, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.StatementType, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", disabled = "disabled", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.StatementType, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" )>Amount</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.TotalSpent, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.TotalSpent, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>



                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-info">Submit</button>
                                @*<a class="btn btn-success" href="~/Product/Index">Back</a>*@
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/CreditNote/Index.cshtml
@model CorporatePortal.Models.CreditNotes.CreditNotesPageModel

@{
    ViewBag.Title = "CreditNotes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>

                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <h2>Credit Notes</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <!-- start project list -->
                <table class="table table-striped projects" id="creditNotesList">
                    <thead>
                        <tr>
                            <th>
                                CreditNoteId
                            </th>
                            <th>
                                CreatedDate
                            </th>
                            <th>
                                CreditProfileId
                            </th>
                            <th>
                                CreditProfileName
                            </th>
                            <th>
                                Amount
                            </th>
                            <th>
                                Description
                            </th>
                            <th>
                                BusinessCentralId
                            </th>
                            <th style="width: 20%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.CreditNotes)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreditNoteId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreditProfileId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreditProfileName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TotalSpent)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BusinessCentralId)
                                </td>
                                <td>
                                    @if (this.User.IsInRole("Admin") || this.User.IsInRole("CorporateAdmin"))
                                    {
                                        @Html.ActionLink("Update", "Update", "CreditNote", new { creditNoteId = item.CreditNoteId }, new { @class = "btn btn-info btn-xs " })
                                        <b>@Html.ActionLink("Delete", "DeleteCreditNote", "CreditNote", new { creditNoteId = item.CreditNoteId }, new { @class = "btn btn-danger btn-xs ", onclick = "return confirm('Are you sure you want to delete this credit note? This action cannot be undone.');" })</b>
                                    }
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.js"></script>

<script>
    $(document).ready(function () {

      

      

    });

</script>

CorporatePortal/CorporatePortal/Views/CreditNote/Update.cshtml
@model CorporatePortal.Models.CreditNotes.UpdateCreditNotePageModel

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    td {
        font-size: larger;
        padding: 10px;
    }

    .tdlabel {
        font-weight: bold;
    }

    .tdheading {
        color: #69c3c4;
        font-weight: bold;
        font-size: 20px;
    }

    .form-control:focus {
        border-color: #CCD0D7;
        box-shadow: none !important
    }
</style>

<style>
</style>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3></h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Update Credit Note<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <br>
                    @using (Html.BeginForm("Update", "CreditNote",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                    FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.CreditNoteId)

                        <div class="form-group">
                            <span class="control-label col-md-3 col-sm-3 col-xs-12 tdheading">General</span>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", disabled = "disabled", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.CreditNoteId, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.CreditProfileId, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12", disabled = "disabled", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.CreditProfileId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CreditProfileName, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.CreditProfileName, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", disabled = "disabled", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.CreditProfileName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.Amount, new { placeholder = "", @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.Description, new { placeholder = "", @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr />

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-info">Submit</button>
                                @*<a class="btn btn-success" href="~/Product/Index">Back</a>*@
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>