CorporatePortal/CorporatePortal/Models/ProductFee/CreateProductFeeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.ProductFee
{
    public class CreateProductFeeModel
    {
        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        public double FinanceFee { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        [Display(Name="SubscriptionFee")]
        public double CardFee { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        public double CardIsueeFee { get; set; } = 5;

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        public double FXFee { get; set; }
    }
}

CorporatePortal/CorporatePortal/Models/ProductFee/ProductFeeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.ProductFee
{
    public class ProductFeeModel
    {
        public int ProductFeeId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreatedDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime UpdatedDate { get; set; }

        
        public string Name { get; set; }

        public double FinanceFee { get; set; }

        public double CardFee { get; set; }

        public double CardIsueeFee { get; set; }

        public double FXFee { get; set; }
    }
}

CorporatePortal/CorporatePortal/Models/ProductFee/ProductFeeResponseModel.cs
using CorporatePortal.Api.Responses;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.ProductFee
{
    public class ProductFeeResponseModel : BaseApiResponse
    {
        public ProductFeeModel ProductFee { get; set; }

        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}

CorporatePortal/CorporatePortal/Models/ProductFee/ProductFeesListPageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.ProductFee
{
    public class ProductFeesListPageModel
    {
        public List<ProductFeeModel> ProductFeeList { get; set; }
    }
}

CorporatePortal/CorporatePortal/Models/ProductFee/UpdateProductFeeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.ProductFee
{
    public class UpdateProductFeeModel
    {
        public int ProductFeeId { get; set; }

        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        public double FinanceFee { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        [Display(Name = "SubscriptionFee")]
        public double CardFee { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        public double CardIsueeFee { get; set; }

        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "Please enter valid value")]
        public double FXFee { get; set; }
    }
}

CorporatePortal/CorporatePortal/Controllers/ProductFeeController.cs
using CorporatePortal.Api;
using CorporatePortal.Api.Requests;
using CorporatePortal.Models.ProductFee;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorporatePortal.Controllers
{
    public class ProductFeeController : Controller
    {
        IApiService _apiService;

        public ProductFeeController(IApiService apiService)
        {
            _apiService = apiService;
            var model = _apiService.GetPortalSummary();
            ViewBag.TopTiles = model.Summary;
        }
        // GET: ProductFee
        public ActionResult Index()
        {
            var response = _apiService.GetProductFeesList();

            var model = new ProductFeesListPageModel
            {
                ProductFeeList = response.ProductFees
            };

            return View(model);
        }

        public ActionResult Create()
        {
            var model = new CreateProductFeeModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreateProductFeeModel model)
        {
            if (!ModelState.IsValid)
            {                
                return View(model);
            }

            ProductFeeModel productFee = new ProductFeeModel
            {
                Name = model.Name,
                CardFee = model.CardFee,
                CardIsueeFee = model.CardIsueeFee,
                FinanceFee = model.FinanceFee,
                FXFee = model.FXFee
            };

            var response = _apiService.CreateProductFee(productFee);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,CorporateAdmin,CorporateManager")]
        [HttpGet]
        public ActionResult DeleteProductFee(int productFeeId)
        {
            var response = _apiService.DeleteProductFee(productFeeId);

            return RedirectToAction("Index");
        }

        public ActionResult Update(int productFeeId)
        {
            var response = _apiService.GetProductFeeById(productFeeId);

            var model = new UpdateProductFeeModel
            {
                ProductFeeId = response.ProductFee.ProductFeeId,
                CardFee = response.ProductFee.CardFee,
                CardIsueeFee = response.ProductFee.CardIsueeFee,
                FinanceFee = response.ProductFee.FinanceFee,
                FXFee = response.ProductFee.FXFee,
                Name = response.ProductFee.Name
            };
                                   
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(UpdateProductFeeModel model)
        {            
            var request = new UpdateProductFeeRequest
            {
                Name = model.Name,
                CardFee = model.CardFee,
                CardIsueeFee = model.CardIsueeFee,
                FinanceFee = model.FinanceFee,
                FXFee = model.FXFee
            };

            var response = _apiService.UpdateProductFee(model.ProductFeeId,request);

            return RedirectToAction("Index");
        }
    }
}

CorporatePortal/CorporatePortal/Views/ProductFee/Create.cshtml
@model CorporatePortal.Models.ProductFee.CreateProductFeeModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    td {
        font-size: larger;
        padding: 10px;
    }

    .tdlabel {
        font-weight: bold;
    }

    .tdheading {
        color: #69c3c4;
        font-weight: bold;
        font-size: 20px;
    }

    .form-control:focus {
        border-color: #CCD0D7;
        box-shadow: none !important
    }
</style>

<style>
</style>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3></h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>New Product Fee<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <br>
                    @using (Html.BeginForm("Create", "ProductFee",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                    FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <span class="control-label col-md-3 col-sm-3 col-xs-12 tdheading">General</span>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FinanceFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.FinanceFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = (0) })
                                @Html.ValidationMessageFor(model => model.FinanceFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CardFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.CardFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = 0 })
                                @Html.ValidationMessageFor(model => model.CardFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CardIsueeFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.CardIsueeFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = 5 })
                                @Html.ValidationMessageFor(model => model.CardIsueeFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FXFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.FXFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = 2.5 })
                                @Html.ValidationMessageFor(model => model.FXFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-info">Submit</button>
                                @*<a class="btn btn-success" href="~/Product/Index">Back</a>*@
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/ProductFee/Index.cshtml
@model CorporatePortal.Models.ProductFee.ProductFeesListPageModel

@{
    ViewBag.Title = "ProductFees";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>

                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <h2>Product Fees</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <!-- start project list -->
                <table class="table table-striped projects" id="spendProfilesList">
                    <thead>
                        <tr>
                            <th>
                                ProductFeeId
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Created
                            </th>
                            <th>
                                Updated
                            </th>
                            <th>
                                FinanceFee
                            </th>
                            <th>
                                SubscriptionFee
                            </th>
                            <th>
                                CardIssueFee
                            </th>
                            <th>
                                FXFee
                            </th>
                            <th style="width: 20%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ProductFeeList)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductFeeId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UpdatedDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FinanceFee)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CardFee)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CardIsueeFee)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FXFee)
                            </td>
                            <td>
                                @if (this.User.IsInRole("Admin") || this.User.IsInRole("CorporateAdmin"))
                                {
                                    @Html.ActionLink("Update", "Update", "ProductFee", new { productFeeId = item.ProductFeeId }, new { @class = "btn btn-info btn-xs " })
                                    <b>@Html.ActionLink("Delete", "DeleteProductFee", new { productFeeId = item.ProductFeeId }, new { @class = "btn btn-danger btn-xs ", onclick = "return confirm('Are you sure you want to delete this product fee? This action cannot be undone.');" })</b>
                                }
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/ProductFee/Update.cshtml
@model CorporatePortal.Models.ProductFee.UpdateProductFeeModel

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    td {
        font-size: larger;
        padding: 10px;
    }

    .tdlabel {
        font-weight: bold;
    }

    .tdheading {
        color: #69c3c4;
        font-weight: bold;
        font-size: 20px;
    }

    .form-control:focus {
        border-color: #CCD0D7;
        box-shadow: none !important
    }
</style>

<style>
</style>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3></h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Update Product Fee<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <br>
                    @using (Html.BeginForm("Update", "ProductFee",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                    FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ProductFeeId)

                        <div class="form-group">
                            <span class="control-label col-md-3 col-sm-3 col-xs-12 tdheading">General</span>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.FinanceFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.FinanceFee, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.FinanceFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CardFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.CardFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12"})
                                @Html.ValidationMessageFor(model => model.CardFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">CardIssueFee</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.CardIsueeFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12"})
                                @Html.ValidationMessageFor(model => model.CardIsueeFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.FXFee, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.FXFee, new { placeholder = "", @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(model => model.FXFee, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr />

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-info">Submit</button>
                                @*<a class="btn btn-success" href="~/Product/Index">Back</a>*@
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>