CorporatePortal/CorporatePortal/Models/CardOrders/BatchOrderCards.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.CardOrders
{
    public class BatchOrderCards
    {
        [Display(Name = "Choose File")]
        public HttpPostedFileBase postedFile { get; set; }
    }
}

CorporatePortal/CorporatePortal/Models/CardOrders/BatchOrderHistory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CorporatePortal.Models.CardOrders
{
    public class BatchOrderHistory
    {
        public int? BatchOrderId { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreatedDate { get; set; }
        public string OrderStatus { get; set; }
        public int Total { get; set; }
        public string ProductCode { get; set; }
        public string CardFileName { get; set; }
    }
}

CorporatePortal/CorporatePortal/Controllers/OrderController.cs
using CorporatePortal.Api;
using CorporatePortal.Api.Requests;
using CorporatePortal.Api.Requests.CardOrder;
using CorporatePortal.Api.Responses;
using CorporatePortal.Models;
using CorporatePortal.Models.CardLoad;
using CorporatePortal.Models.CardOrders;
using CorporatePortal.Models.User;
using Excel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorporatePortal.Controllers
{
    [Authorize(Roles = "Admin,CorporateAdmin,CorporateManager,CorporateEmployee")]
    public class OrderController : Controller
    {
        IApiService _apiService;

        public OrderController(IApiService apiService)
        {
          _apiService = apiService;
            var model = _apiService.GetPortalSummary();
            ViewBag.TopTiles = model.Summary;
        }

        public ActionResult Index()
        {
            var batchOrdersList = _apiService.GetOrderHistory().Orders.OrderByDescending(o => o.BatchOrderId).Reverse().ToList();
            var individualOrdersList = _apiService.GetIndividualOrderHistory().Orders;
            var virtualCards = _apiService.GetVirtualCards();
            var accounts = _apiService.GetCorporateAccountsFundsSummary();
            var model = new OrderHomePageModel
            {
                batchOrders = batchOrdersList,
                individualOrders = individualOrdersList,
                AccountsList = accounts.AccountsList,
                VirtualCards = virtualCards.VirtualCards
            };

            return View(model);
        }

        #region BatchOrder
        public ActionResult BatchOrderCards()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BatchOrderCardsExcel(BatchOrderCards cardFile)
        {
            if (cardFile.postedFile == null || cardFile.postedFile.ContentLength < 0)
            {
                ModelState.AddModelError("", "Invalid file!");
                TempData["FailureMessage"] = "Invalid file!";
                return View("BatchOrderCards", cardFile);
            }

            var cardOrders = new List<OrderIndividualCardRequest>();

            if (cardFile.postedFile != null && cardFile.postedFile.ContentLength > 0)
            {
                //ExcelDataReader works on binary excel file
                Stream stream = cardFile.postedFile.InputStream;
                //We need to written the Interface.
                IExcelDataReader reader = null;
                if (cardFile.postedFile.FileName.EndsWith(".xls"))
                {
                    //reads the excel file with .xls extension
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                }
                else if (cardFile.postedFile.FileName.EndsWith(".xlsx"))
                {
                    //reads excel file with .xlsx extension
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }
                else
                {
                    //Shows error if uploaded file is not Excel file
                    ModelState.AddModelError("", "Invalid file format. Please upload an excel file!");
                    TempData["FailureMessage"] = "Invalid file format. Please upload an excel file!";
                    return View("BatchOrderCards",cardFile);
                }
                //treats the first row of excel file as Coluymn Names
                reader.IsFirstRowAsColumnNames = true;
                //Adding reader data to DataSet()
                DataSet result = reader.AsDataSet();
                reader.Close();

                var table = result.Tables[0];
                
                for (int i = 0; i < table.Rows.Count; i++)
                {
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[i].ToString()))
                    {
                        table.Rows.RemoveAt(i);
                    }
                }

                var invalidRows = new List<DataRow>();

                var invalidRecords = table.Clone();

                for (int i = 0; i < table.Rows.Count; i++)
                {
                    //row id
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[0].ToString()))
                    {                       
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    //productcode
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[1].ToString()))
                    {
                      
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }
                    
                    //card design
                    //if (string.IsNullOrEmpty(values[2]))
                    //{
                    //    invalidRecordsModel.Records.Add(inputLine);
                    //    Lines.Remove(inputLine);
                    //    continue;
                    //}


                    //first name
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[3].ToString()) || (table.Rows[i].ItemArray[3].ToString().Length > 20))
                    {
                       
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);

                        continue;
                    }

                    //last name
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[4].ToString()) || (table.Rows[i].ItemArray[4].ToString().Length > 20))
                    {
                        
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    //NameOnCard
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[5].ToString()) || (table.Rows[i].ItemArray[5].ToString().Length > 20))
                    {
                        
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    //// AddtionalEmbossCardData
                    //if (string.IsNullOrEmpty(table.Rows[i].ItemArray[6].ToString()))
                    //{

                    //    invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                    //    continue;
                    //}


                    //dob
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[7].ToString()))
                    {
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;                           
                    }
                    else
                    {
                        var dob = table.Rows[i].ItemArray[7].ToString();
                        DateTime dt;
                        if (DateTime.TryParseExact(dob, "dd/MM/yyyy", null, DateTimeStyles.None, out dt) != true)
                        {
                            invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                            continue;
                        }
                    }

                    //email
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[8].ToString()) || (table.Rows[i].ItemArray[8].ToString().Length > 64))
                    {
                        
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    //mobile
                    //if (string.IsNullOrEmpty(values[9]))
                    //{
                    //    invalidRecordsModel.Records.Add(inputLine);
                    //    Lines.Remove(inputLine);
                    //    continue;
                    //}

                    //address1
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[10].ToString()) || (table.Rows[i].ItemArray[10].ToString().Length > 35))
                    {
                   
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    ////address2
                    //if (string.IsNullOrEmpty(values[11]))
                    //{
                    //    invalidRecordsModel.Records.Add(inputLine);
                    //    Lines.Remove(inputLine);
                    //    continue;
                    //}

                    ////address3
                    //if (string.IsNullOrEmpty(values[12]))
                    //{
                    //    invalidRecordsModel.Records.Add(inputLine);
                    //    Lines.Remove(inputLine);
                    //    continue;
                    //}

                    //city
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[13].ToString()) || (table.Rows[i].ItemArray[13].ToString().Length > 20))
                    {
                        
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    ////state
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[14].ToString()) || (table.Rows[i].ItemArray[14].ToString().Length > 20))
                    {

                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    //country code
                    if (string.IsNullOrEmpty(table.Rows[i].ItemArray[15].ToString()) || (table.Rows[i].ItemArray[15].ToString().Length != 3))
                    {
                        
                        invalidRecords.Rows.Add(table.Rows[i].ItemArray);
                        continue;
                    }

                    //postcode

CorporatePortal/CorporatePortal/Views/Order/BatchOrderCards.cshtml
@model CorporatePortal.Models.CardOrders.BatchOrderCards

@{
    ViewBag.Title = "BatchOrderCards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>New Batch Order</h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>

                    @using (Html.BeginForm("BatchOrderCardsExcel", "Order", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-horizontal form-label-left">
                            @*<div class="form-group">
                                    @Html.LabelFor(model => model.Product.ProductCode, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.Product.ProductCode, Model.Products, new { @class = "form-control col-md-7 col-xs-12" })
                                        @Html.ValidationMessageFor(model => model.Product.ProductCode)
                                    </div>
                                </div>*@

                            <div class="form-group">
                                @Html.LabelFor(model => model.postedFile, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    @Html.TextBoxFor(model => model.postedFile, new { @class = "form-control col-md-7 col-xs-12", type = "file" })
                                    @Html.ValidationMessageFor(model => model.postedFile)
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="~/Order/Index">
                                        <input type="button" value="Back" class="btn btn-info" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="x_panel">
                <div class="x_title">
                    <h2> <small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <pre>
                        <b>Valid format :  RowId, ProductCode, CardDesign, Firstname, Lastname, NameOnCard, AdditionalCardEmbossData, Dob, Email, Mobile, Address1, Address2, Address3, City, County, CountryCode, PostCode</b>
                    <br/>
                    <b>@Html.ActionLink("Download Template", "DownloadFile", "Order", new { @class = "btn btn-success btn-xs" })</b>
                    </pre>
                    
                </div>
            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/Order/BatchOrderHistory.cshtml
@model IEnumerable<CorporatePortal.Models.CardOrders.BatchOrderHistory>

@{
    ViewBag.Title = "BatchOrderHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .ct-active {
        outline: none;
        border-color: #9ecaed;
        box-shadow: 0 0 10px #9ecaed;
        font-weight: bold;
    }
</style>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Batch Orders History</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <p></p>

                @Html.ActionLink("New Order", "BatchOrderCards", "Order", new { @class = "btn btn-info" })
                <table class="table table-striped projects" id="batchorderhistory">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.BatchOrderId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Total)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CardFileName)
                            </th>
                            <th style="width: 20%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.BatchOrderId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedDate)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Total)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CardFileName)
                                </td>
                                <td>
                                    @Html.ActionLink("Details", "GetBatchOrderDetails", "Order", new { batchOrderId = item.BatchOrderId }, new { @class = "btn btn-primary btn-xs" })
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>

<script src="~/Assets/PortalLayout1/vendors/jquery/dist/jquery.min.js"></script>
<script src="~/Assets/PortalLayout1/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

<script>
    $(document).ready(function () {
          var success = @((TempData["Success"] != null).ToString().ToLower());
        if (success == true) {
            bootbox.alert({
                message: "@(TempData["Success"])",
                backdrop: true,
                size: 'large',
                className: 'bb-alternate-modal',
                callback: function () {
                    $("#batchorderhistory tbody tr:first").hide().fadeIn(1000).addClass('ct-active');
                }
            });
           
        }
    });
</script>

CorporatePortal/CorporatePortal/Views/Order/BatchOrderSummary.cshtml
@model CorporatePortal.Models.CardOrders.BatchOrder
@{
    ViewBag.Title = "BatchOrderCardsSummary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Summary</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>                  
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @foreach (var item in Model.CardOrders.GroupBy(x => x.ProductCode))
                {
                <h4 display:inline">
                    <span style="font-size:x-large;color:#5bc0de">ProductCode : ></span><span style="margin-left:5px">@item.Key</span> 
                    <span style="font-size:x-large; margin-left:20px;color:#5bc0de">Total Cards : ></span> <span style="margin-left:5px">@item.Count()</span> 
                    <span style="font-size:x-large;margin-left:20px;color:#5bc0de">FileName : ></span><span style="margin-left:5px">@Model.CardOrders[0].cardFileName</span>
                </h4>
                  
                    <table class="table table-striped projects" id="batchOrderSummary">

                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].ProductCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].CardDesign)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].FirstName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].LastName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].NameOnCard)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].AdditionalCardEmbossData)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].Dob)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].RecipientEmail)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].Mobile)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].Address1)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].Address2)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].Address3)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].City)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].State)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].ISOCountryCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CardOrders[1].PostCode)
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var order in item)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(model => order.ProductCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.CardDesign)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.NameOnCard)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.AdditionalCardEmbossData)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.Dob)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.RecipientEmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.Mobile)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.Address1)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.Address2)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.Address3)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.City)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.State)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.ISOCountryCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => order.PostCode)
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>

                }
            </div>
           
        </div>
    </div>
    <div class="col-md-12">
        <div class="text-center">
            @using (Html.BeginForm("SubmitOrder", "Order", FormMethod.Post))
            {
                for (int i = 0; i < Model.CardOrders.Count; i++)
                {
                    @Html.HiddenFor(m => m.CardOrders[i].FirstName)
                    @Html.HiddenFor(m => m.CardOrders[i].LastName)
                    @Html.HiddenFor(m => m.CardOrders[i].NameOnCard)
                    @Html.HiddenFor(m => m.CardOrders[i].Address1)
                    @Html.HiddenFor(m => m.CardOrders[i].Address2)
                    @Html.HiddenFor(m => m.CardOrders[i].Address3)
                    @Html.HiddenFor(m => m.CardOrders[i].RecipientEmail)
                    @Html.HiddenFor(m => m.CardOrders[i].City)
                    @Html.HiddenFor(m => m.CardOrders[i].ISOCountryCode)
                    @Html.HiddenFor(m => m.CardOrders[i].PostCode)
                    @Html.HiddenFor(m => m.CardOrders[i].ProductCode)
                    @Html.HiddenFor(m => m.CardOrders[i].Dob)
                    @Html.HiddenFor(m => m.CardOrders[i].State)
                    @Html.HiddenFor(m => m.CardOrders[i].cardFileName)
                    @Html.HiddenFor(m => m.CardOrders[i].CardDesign)
                    @Html.HiddenFor(m => m.CardOrders[i].AdditionalCardEmbossData)
                }

                <input class="btn btn-success" type="submit" value="Order Cards" />
                <a href="~/Order/BatchOrderCards">
                    <input type="button" value="Back" class="btn btn-info" />
                </a>
            }
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/Order/InvalidBatchOrderExcel.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "InvalidBatchOrderFileExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Orders</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <p><b style="color:red"> Following <span style="font-size:larger">@Model.Rows.Count</span> records are invalid. Please correct them in the file and try again!</b></p>
                
                @Html.ActionLink("New Order", "BatchOrderCards", "Order", new { @class = "btn btn-success" })
                <br/><br/>
                <!-- start project list -->
                <table class="table table-striped projects" id="batchorderhistory">
                    <thead>
                        <tr>
                            @foreach (DataColumn col in Model.Columns)
                            {
                                <th>@col.ColumnName</th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (DataRow row in Model.Rows)
                        {
                            <tr>
                                @foreach (DataColumn col in Model.Columns)
                                {
                                    <td>@row[col.ColumnName]</td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>