CorporatePortal/CorporatePortal/Models/Product/UpdatePurchaseCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorporatePortal.Models.Product
{
    public class UpdatePurchaseCategoryViewModel
    {
        public PurchaseCategory PurchaseCategory { get; set; }

        public IList<SelectListItem> Mcc { get; set; }
    }
}

CorporatePortal/CorporatePortal/Controllers/SpendProfileController.cs
using CorporatePortal.Api;
using CorporatePortal.Api.Requests;
using CorporatePortal.Models.Product;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CorporatePortal.Controllers
{
    public class SpendProfileController : Controller
    {
        IApiService _apiService;

        public SpendProfileController(IApiService apiService)
        {
            _apiService = apiService;
            var model = _apiService.GetPortalSummary();
            ViewBag.TopTiles = model.Summary;
        }

        // GET: SpendProfile
        public ActionResult Index()
        {
            var response = _apiService.GetSpendProfileList();

            var model = new SpentProfileListPageModel
            {
                ProfileList = response.SpendProfileList
            };

            return View(model);
        }

        public ActionResult Create()
        {
            var model = new SpendProfileModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(SpendProfileModel model)
        {
           var response =  _apiService.CreateSpendProfile(model);

            return RedirectToAction("Index");
        }

        public ActionResult Update(int spendProfileId)
        {
            var spendProfileResponse = _apiService.GetSpendProfileById(spendProfileId);

            var purchaseCategoriesResponse = _apiService.GetPurchaseCategoriesBySpendProfile(spendProfileId);

            var allPurchaseCategoriesResponse = _apiService.GetPurchaseCategories();

            var allCats = allPurchaseCategoriesResponse.Categories;
            var selectedCats = purchaseCategoriesResponse.Categories;

            var model = new UpdateSpendProfileViewModel();

            model.SpendProfile = spendProfileResponse.SpendProfile;

            var categories = new List<SelectListItem>();


            foreach (var allCategories in allCats.ToList())
            {
                foreach (var selectedCategories in selectedCats.ToList())
                {
                    if(allCategories.Id == selectedCategories.Id)
                    {
                        categories.Add(new SelectListItem
                        {
                            Text = allCategories.Name,
                            Value = allCategories.Id.ToString(),
                            Selected = true
                        });

                        allCats.Remove(allCategories);
                    }
                }
            }

            foreach (var cats in allCats)
            {
                categories.Add(new SelectListItem
                {
                    Text = cats.Name,
                    Value = cats.Id.ToString(),
                    Selected = false
                });
            }
         

            model.PurchaseCategories = categories;

            return View(model);
        }

        [HttpPost]
        public ActionResult Update(UpdateSpendProfileViewModel model)
        {
            var spendProfile = model.SpendProfile;

            var categoriesToUpdate = new List<PurchaseCategory>();

            foreach (var cat in model.PurchaseCategories.ToList())
            {
                if(cat.Selected == true)
                {
                    categoriesToUpdate.Add(new PurchaseCategory
                    {
                        Id = Convert.ToInt16(cat.Value),
                        Name = cat.Text
                    });
                }
            }

            var request = new UpdateSpendProfileRequest
            {
                SpendProfile = model.SpendProfile,
                PurchaseCategories = categoriesToUpdate
            };

            var response = _apiService.UpdateSpendProfile(request);

            return RedirectToAction("Index");
        }

        public ActionResult PurchaseCategories()
        {
            var response = _apiService.GetPurchaseCategories();
            var model = new PurchaseCategoryPageModel
            {
                purchaseCategories = response.Categories
            };

            return View(model);
        }

        public ActionResult CreatePurchaseCategory()
        {
            var model = new PurchaseCategory();

            return View(model);
        }

        [HttpPost]
        public ActionResult CreatePurchaseCategory(PurchaseCategory model)
        {
            var response = _apiService.CreatePurchaseCategory(model);

            return RedirectToAction("PurchaseCategories");
        }

        public ActionResult UpdatePurchaseCategory(int categoryId)
        {
           var purchaseCategoriesResponse = _apiService.GetPurchaseCategories().Categories.Where(p => p.Id == categoryId).FirstOrDefault();

            var purchaseCategoryMccResponse = _apiService.GetMerchantCodesByPurchaseCategory(categoryId);

            var allMccResponse = _apiService.GetMerchantCodes();


            var all = allMccResponse.MerchantCodes;
            var selected = purchaseCategoryMccResponse.MerchantCodes;

            var model = new UpdatePurchaseCategoryViewModel();

            model.PurchaseCategory = purchaseCategoriesResponse;

            var mccList = new List<SelectListItem>();

            foreach (var allCategories in all.ToList())
            {
                foreach (var selectedCategories in selected.ToList())
                {
                    if (allCategories.MerchantCode == selectedCategories.MerchantCode)
                    {
                        mccList.Add(new SelectListItem
                        {
                            Text = allCategories.MerchantCode + " || " + allCategories.Description,
                            Value = allCategories.MerchantCode.ToString(),
                            Selected = true
                        });

                        all.Remove(allCategories);
                    }
                }
            }

            foreach (var cats in all)
            {
                mccList.Add(new SelectListItem
                {
                    Text = cats.MerchantCode + " || " + cats.Description,
                    Value = cats.MerchantCode.ToString(),
                    Selected = false
                });
            }

            model.Mcc = mccList;

            return View(model);
        }

        [HttpPost]
        public ActionResult UpdatePurchaseCategory(UpdatePurchaseCategoryViewModel model)
        {
            var purchaseCategory = model.PurchaseCategory;

            var mccToUpdate = new List<MerchantCodeModel>();

            foreach (var cat in model.Mcc.ToList())
            {
                if (cat.Selected == true)
                {
                    mccToUpdate.Add(new MerchantCodeModel
                    {
                        MerchantCode = Convert.ToInt16(cat.Value),
                        Description = cat.Text
                    });
                }
            }

            var request = new UpdatePurchaseCategoryRequest
            {
                PurchaseCategory = model.PurchaseCategory,
                MerchantCodes = mccToUpdate
            };

            var response = _apiService.UpdatePurchaseCategory(request);

            return RedirectToAction("PurchaseCategories");
          
        }

        [Authorize(Roles = "Admin,CorporateAdmin,CorporateManager")]
        [HttpGet]
        public ActionResult DeleteSpendProfile(int spendProfileId)
        {
            var response = _apiService.DeleteSpendProfile(spendProfileId);

            return RedirectToAction("Index");
        }
    }
}

CorporatePortal/CorporatePortal/Views/SpendProfile/Create.cshtml
@model CorporatePortal.Models.Product.SpendProfileModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    td {
        font-size: larger;
        padding: 10px;
    }

    .tdlabel {
        font-weight: bold;
    }

    .tdheading {
        color: #69c3c4;
        font-weight: bold;
        font-size: 20px;
    }

    .form-control:focus {
        border-color: #CCD0D7;
        box-shadow: none !important
    }
</style>

<style>
</style>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3></h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>New Spend Profile<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <br>
                    @using (Html.BeginForm("Create", "SpendProfile",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                    FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <span class="control-label col-md-3 col-sm-3 col-xs-12 tdheading">General</span>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ProfileName, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.ProfileName, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.ProfileName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxDailyTxnTotalValue, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MaxDailyTxnTotalValue, new { placeholder = "Cannot exceed £10000", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MaxDailyTxnTotalValue > 0 ? Model.MaxDailyTxnTotalValue.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MaxDailyTxnTotalValue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxWeeklyTxnValue, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MaxWeeklyTxnValue, new { placeholder = "Cannot exceed £15000", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MaxWeeklyTxnValue > 0 ? Model.MaxWeeklyTxnValue.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MaxWeeklyTxnValue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxMonthlyTxnValue, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MaxMonthlyTxnValue, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MaxWeeklyTxnValue > 0 ? Model.MaxWeeklyTxnValue.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MaxMonthlyTxnValue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxSingleTxnValue, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MaxSingleTxnValue, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MaxSingleTxnValue > 0 ? Model.MaxSingleTxnValue.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MaxSingleTxnValue, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.DailyVelocity, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.DailyVelocity, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = (Model.DailyVelocity > 0 ? Model.DailyVelocity.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.DailyVelocity, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.WeeklyVelocity, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.WeeklyVelocity, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = (Model.WeeklyVelocity > 0 ? Model.WeeklyVelocity.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.WeeklyVelocity, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MonthlyVelocity, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MonthlyVelocity, new { placeholder = "", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MonthlyVelocity > 0 ? Model.MonthlyVelocity.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MonthlyVelocity, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-info">Submit</button>
                                @*<a class="btn btn-success" href="~/Product/Index">Back</a>*@
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/SpendProfile/CreatePurchaseCategory.cshtml
@model CorporatePortal.Models.Product.PurchaseCategory

@{
    ViewBag.Title = "Create Purchase Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    td {
        font-size: larger;
        padding: 10px;
    }

    .tdlabel {
        font-weight: bold;
    }

    .tdheading {
        color: #69c3c4;
        font-weight: bold;
        font-size: 20px;
    }

    .form-control:focus {
        border-color: #CCD0D7;
        box-shadow: none !important
    }
</style>

<style>
</style>

<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3></h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>New Purchase Category<small></small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <br>
                    @using (Html.BeginForm("CreatePurchaseCategory", "SpendProfile",
                    new { ReturnUrl = ViewBag.ReturnUrl },
                    FormMethod.Post, new { @class = "form-horizontal form-label-left" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <span class="control-label col-md-3 col-sm-3 col-xs-12 tdheading">General</span>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control col-md-7 col-xs-12" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxDailyTxnTotalValue, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MaxDailyTxnTotalValue, new { placeholder = "Cannot exceed £10000", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MaxDailyTxnTotalValue > 0 ? Model.MaxDailyTxnTotalValue.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MaxDailyTxnTotalValue, "", new { @class = "text-danger" })
                            </div>
                        </div>                       

                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxWeeklyTxnValue, htmlAttributes: new { @class = "control-label col-md-3 col-sm-3 col-xs-12" })
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(model => model.MaxWeeklyTxnValue, new { placeholder = "Cannot exceed £15000", @class = "form-control col-md-7 col-xs-12", @Value = (Model.MaxWeeklyTxnValue > 0 ? Model.MaxWeeklyTxnValue.ToString() : string.Empty) })
                                @Html.ValidationMessageFor(model => model.MaxWeeklyTxnValue, "", new { @class = "text-danger" })
                            </div>
                        </div>                      

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <button type="submit" class="btn btn-info">Submit</button>
                                @*<a class="btn btn-success" href="~/Product/Index">Back</a>*@
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/SpendProfile/Index.cshtml
@model CorporatePortal.Models.Product.SpentProfileListPageModel

@{
    ViewBag.Title = "SpendProfiles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>

                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <h2>Spend Profiles</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <!-- start project list -->
                <table class="table table-striped projects" id="spendProfilesList">
                    <thead>
                        <tr>
                            <th>
                                SpendProfileId
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Max Daily Txn Val
                            </th>
                            <th>
                                Max Weekly Txn Val
                            </th>
                            <th>
                                Max Monthly Txn Val
                            </th>
                            <th>
                                Max Single Txn Val
                            </th>
                            <th>
                                Daily Velocity
                            </th>
                            <th>
                                Weekly Velocity
                            </th>
                            <th>
                                Monthly Velocity
                            </th>
                            <th style="width: 20%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ProfileList)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.SpendProfileId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProfileName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxDailyTxnTotalValue)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxWeeklyTxnValue)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxMonthlyTxnValue)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxSingleTxnValue)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DailyVelocity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.WeeklyVelocity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MonthlyVelocity)
                            </td>
                            <td>
                                @if (this.User.IsInRole("Admin") || this.User.IsInRole("CorporateAdmin"))
                                {
                                    @Html.ActionLink("Update", "Update", "SpendProfile", new { spendProfileId = item.SpendProfileId }, new { @class = "btn btn-info btn-xs " })
                                    <b>@Html.ActionLink("Delete", "DeleteSpendProfile", new { spendProfileId = item.SpendProfileId }, new { @class = "btn btn-danger btn-xs ", onclick = "return confirm('Are you sure you want to delete this spend profile? All associated products will be updated. This action cannot be undone.');" })</b>
                                }
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>

CorporatePortal/CorporatePortal/Views/SpendProfile/PurchaseCategories.cshtml
@model CorporatePortal.Models.Product.PurchaseCategoryPageModel

@{
    ViewBag.Title = "Purchase Categories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>

                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <h2>Purchase Categories</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <!-- start project list -->
                <table class="table table-striped projects" id="purchaseCategoriesList">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                Max Daily Txn Val
                            </th>
                            <th>
                                Max Weekly Txn Val
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.purchaseCategories)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>                           
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxDailyTxnTotalValue)
                            </td>                          
                            <td>
                                @Html.DisplayFor(modelItem => item.MaxWeeklyTxnValue)
                            </td>                           
                            <td>
                                @if (this.User.IsInRole("Admin") || this.User.IsInRole("CorporateAdmin") || this.User.IsInRole("CorporateManager"))
                                {
                                    @Html.ActionLink("Update", "UpdatePurchaseCategory", "SpendProfile", new { categoryId = item.Id }, new { @class = "btn btn-info btn-xs " })
                                }
                            </td>
                        </tr>
                        }

                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>